export const fakeChats = [
	{
		id: 1,
		name: "Mark",
		lastMessage: "I don´t know who you are...",
		unreadMessages: 3,
		date: "3:44 pm",
	},
	{
		id: 2,
		name: "Hidegram",
		lastMessage: "Hidegram web was updated",
		unreadMessages: 1,
		date: "3:44 pm",
	},
	{
		id: 3,
		name: "Alice",
		lastMessage: "Why?",
		unreadMessages: 19,
		date: "3:44 pm",
	},
	{
		id: 4,
		name: "Saved Messages",
		lastMessage: "image.jpeg",
		unreadMessages: 3,
		date: "Mon",
	},
	{
		id: 5,
		name: "Mark",
		lastMessage: "I don´t know who you are...",
		unreadMessages: 3,
		date: "3:44 pm",
	},
	{
		id: 6,
		name: "Hidegram",
		lastMessage: "Hidegram web was updated",
		unreadMessages: 1,
		date: "3:44 pm",
	},
	{
		id: 7,
		name: "Alice",
		lastMessage: "Why?",
		unreadMessages: 19,
		date: "3:44 pm",
	},
	{
		id: 8,
		name: "Saved Messages",
		lastMessage: "image.jpeg",
		unreadMessages: 3,
		date: "Mon",
	},
	{
		id: 9,
		name: "Mark",
		lastMessage: "I don´t know who you are...",
		unreadMessages: 3,
		date: "3:44 pm",
	},
	{
		id: 10,
		name: "Hidegram",
		lastMessage: "Hidegram web was updated",
		unreadMessages: 1,
		date: "3:44 pm",
	},
	{
		id: 11,
		name: "Alice",
		lastMessage: "Why?",
		unreadMessages: 19,
		date: "3:44 pm",
	},
	{
		id: 12,
		name: "Saved Messages",
		lastMessage: "image.jpeg",
		unreadMessages: 3,
		date: "Mon",
	},
];

export const fakeMessages = [
	{
		id: "1",
		type: "text",
		content: "Hey, how's it going?",
		sender: { id: "user1", name: "Alice" },
		timestamp: "2022-03-15T12:30:00Z",
		status: "sent",
		isRead: true,
	},
	{
		id: "2",
		type: "text",
		content:
			"Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure eaque minus, laborum tenetur ullam numquam accusamus impedit nemo optio fugit.",
		sender: { id: "user2", name: "Bob" },
		timestamp: "2022-03-15T12:35:00Z",
		status: "delivered",
		isRead: false,
	},
	{
		id: "3",
		type: "text",
		content:
			"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Fugit alias minus quidem. A et maiores vero, enim minima quos necessitatibus maxime atque id quia veniam impedit, omnis, vel cupiditate totam?",
		sender: { id: "user1", name: "Alice" },
		timestamp: "2022-03-15T12:40:00Z",
		status: "read",
		isRead: true,
	},
	{
		id: "4",
		type: "text",
		content:
			"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Fugit alias minus quidem. A et maiores vero",
		sender: { id: "user1", name: "Jon" },
		timestamp: "2022-03-15T12:40:00Z",
		status: "read",
		isRead: true,
	},
	{
		id: "5",
		type: "text",
		content: "Lorem, ipsum dolor sit amet",
		sender: { id: "user1", name: "Bob" },
		timestamp: "2022-03-15T12:40:00Z",
		status: "read",
		isRead: true,
	},
	{
		id: "6",
		type: "text",
		content:
			"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Fugit alias minus quidem. A et maiores vero, enim minima",
		sender: { id: "user1", name: "Alice" },
		timestamp: "2022-03-15T12:40:00Z",
		status: "read",
		isRead: true,
	},
	{
		id: "7",
		type: "text",
		content: "Lorem, ipsum dolor sit amet",
		sender: { id: "user1", name: "Alice" },
		timestamp: "2022-03-15T12:40:00Z",
		status: "read",
		isRead: true,
	},
	{
		id: "8",
		type: "image",
		content: "/image-example.png",
		sender: { id: "user2", name: "Bob" },
		timestamp: "2022-03-15T12:45:00Z",
		status: "sent",
		isRead: false,
	},
	{
		id: "9",
		type: "image",
		content: "/horizontal.png",
		sender: { id: "user1", name: "Alice" },
		timestamp: "2022-03-15T12:50:00Z",
		status: "delivered",
		isRead: true,
	},
].reverse();

export const myData = [
	{ title: "J Black", id: String(Math.random()).slice(8) },
	{ title: "Wife 2", id: String(Math.random()).slice(8) },
	{ title: "Note 12", id: String(Math.random()).slice(8) },
	{ title: "Margus", id: String(Math.random()).slice(8) },
	{ title: "Ketamin pro", id: String(Math.random()).slice(8) },
	{ title: "Wife", id: String(Math.random()).slice(8) },
	{ title: "Kitten", id: String(Math.random()).slice(8) },
	{ title: "Warum nicht", id: String(Math.random()).slice(8) },
	{ title: "Wife 2", id: String(Math.random()).slice(8) },
];
